### PR TITLE
Support panning using a touchpad or scrollwheel

### PR DESCRIPTION
**Pull request by comonoidial**
This could use some testing on non windows devices.
Replaces PR #440.

Unfortunately I could not get zooming to work on touchpad too, and I don't know whether to blame the OS or JavaFX for that.

### CODE REVIEW

**Comment by wandernauta** [comment]
Seems to work on Linux - I can pan in both directions with two-finger touchpad scroll.

Would it make sense to add a 'reverse scroll direction' preference option? It feels a bit more natural to me reversed, but I think that would very much be a personal preference thing.

**Comment by TheMSB** [comment]
> wandernauta

I think adding a preference option for reverse scrolling is a good idea that would require much extra work to implement. Some people just really prefer scrolling one way or the other so it could help with the usability of the program.

**Comment by comonoidial** [comment]
I will add a preference. What is the commonly agreed default on this?

**Comment by wandernauta** [comment]
I think the direction you're using in this PR (positive scroll) is a reasonable default.

**Comment by andrewdavidmackenzie** [comment]
At least on Mac, the reverse scroll thing is an OS setting, and doesn't
need handing by the app

**Comment by andrewdavidmackenzie** [comment]
I have tested on Mac.
- works fine, direction is the direction set by the OS
- I checked that if you switch the OS scroll behaviour it switches also, so no further changes needed there

I notice that if you have the cursor on top of a popped-up toolbar, then the scrolling doesn't work....I assume because it's on top of the layer that where you are processing the scroll events....the toolbar layer must consume them.
To fix I guess you'd need to handle scroll events on the top (touch?) layer, OR, make sure the toolbar doesn't consume scroll events and they fall through to the lower layers.

In my branch for scrolling, I did the initial displacement of the background (as you suggested) so it is harder to get to see the white border. Maybe could do too?
A better fix, would be if we had scrolled to the edge of the canvas and not allow scrolling beyond it...so you can never see the white.

Same thing for zoom out, I thought if we zoom out beyond the size of the canvas, then trancate position to extent of canvas and avoid seeing the white around it.

**Comment by comonoidial** [comment]
The toolbar had a overreaching eventhandler consuming scroll event, which is fixed in last commit.

I didn't change displacement now, because whether that is needed depends on the resolution of #439.

Limiting the scrolling to the edge of the canvas is a separate issue, which has multiple possible design alternatives.

**Comment by andrewdavidmackenzie** [comment]
+1 Fine to merge for me then.

**Pull request merged**
