### PR TITLE
Add keyboard shortcuts to most menu items

### PR DESCRIPTION
**Pull request by andrewdavidmackenzie**
Added Keyboard shortcuts for most menu items.
NOTE: There is a strange bug on Mac that Command & '-' to zoom out doesn't work on JavaFX.

Moved the zoom() method into ToplevelPane() which is the Pane it actually changes the view of and hence belongs to.

Moved the showPreferences() and showInspector() methods into MenuActions as they can be totally self-contained in there.

Added unit tests for some of the menu actions

### CODE REVIEW

**Comment by andrewdavidmackenzie** [comment]
OK, now I'm confused....fails because of same error as before... but have to stop today - will have to look at this tomorrow.

**Comment by andrewdavidmackenzie** [comment]
mvn test in my local copy works fine. This is annoying....

**Comment by comonoidial** [comment]
Maybe these new tests should be marked as integration tests like in the previous PR.

**Comment by andrewdavidmackenzie** [comment]
I may have to.

But what I don't understand is that the test that fails are the ones in ToplevelPaneTest.java which hasn't changed in this branch versus master, and master is green.

**Comment by wandernauta** [comment]
When I run integration tests locally under xvfb, I get `MenuActionsTest` being in error rather than `ToplevelPaneTest` - those tests seem to make a real MenuActions instance, could that be it?

**Comment by andrewdavidmackenzie** [comment]
I don't think so. Travis clearly names ToplevelPanelTest ... 

When I run locally, all pass with zero issues...

Conclusion, the testing with xvfb varies with platform and classes being tested :-(

**Comment by andrewdavidmackenzie** [comment]
For reference: 

> mvn verify
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building viskell 0.1
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- antlr4-maven-plugin:4.5:antlr4 (default) @ viskell ---
[INFO] ANTLR 4: Processing source directory /Users/andrew/workspace/viskell/Code/src/main/antlr4
[INFO] Processing grammar: nl/utwente/viskell/haskell/typeparser/Type.g4
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ viskell ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 50 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ viskell ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 106 source files to /Users/andrew/workspace/viskell/Code/target/classes
[INFO] /Users/andrew/workspace/viskell/Code/src/main/java/nl/utwente/viskell/ui/ToplevelPane.java: Some input files use unchecked or unsafe operations.
[INFO] /Users/andrew/workspace/viskell/Code/src/main/java/nl/utwente/viskell/ui/ToplevelPane.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ viskell ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/andrew/workspace/viskell/Code/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ viskell ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ viskell ---
[INFO] Surefire report directory: /Users/andrew/workspace/viskell/Code/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running nl.utwente.viskell.ghcj.GhciEvaluatorTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.846 sec
Running nl.utwente.viskell.ghcj.GhciSessionTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.25 sec
Running nl.utwente.viskell.haskell.env.HaskellCatalogTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.406 sec
Running nl.utwente.viskell.haskell.expr.ApplyTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.049 sec
Running nl.utwente.viskell.haskell.expr.ExprTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.022 sec
Running nl.utwente.viskell.haskell.expr.IdentTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running nl.utwente.viskell.haskell.expr.LambdaTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.278 sec
Running nl.utwente.viskell.haskell.expr.ValueTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running nl.utwente.viskell.haskell.type.ApplyTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.527 sec
Running nl.utwente.viskell.haskell.type.BubbleTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running nl.utwente.viskell.haskell.type.ClassesTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.713 sec
Running nl.utwente.viskell.haskell.type.FunTypeTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec
Running nl.utwente.viskell.haskell.type.LambdaTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.702 sec
Running nl.utwente.viskell.haskell.type.SharingTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec
Running nl.utwente.viskell.haskell.type.TypeConTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running nl.utwente.viskell.haskell.type.TypeTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec
Running nl.utwente.viskell.haskell.type.UnificationTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.356 sec
Running nl.utwente.viskell.haskell.typeparser.TypeBuilderTest
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 sec
Running nl.utwente.viskell.ui.MenuActionsTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.956 sec

Results :

Tests run: 69, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- xml-maven-plugin:1.0:validate (default) @ viskell ---
[INFO] No matching files found for ValidationSet with public ID null, system ID src/main/resources/catalog/catalog.xsd.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ viskell ---
[INFO] Building jar: /Users/andrew/workspace/viskell/Code/target/viskell-0.1.jar
[INFO] 
[INFO] --- maven-assembly-plugin:2.5.3:single (make-assembly) @ viskell ---
Adding org.apache.maven.artifact.repository.layout.ArtifactRepositoryLayoutdefault
Adding org.apache.maven.artifact.repository.layout.ArtifactRepositoryLayoutlegacy
Adding org.apache.maven.artifact.handler.manager.ArtifactHandlerManager
Adding org.apache.maven.artifact.handler.ArtifactHandlerejb
Adding org.apache.maven.artifact.handler.ArtifactHandlerjar
Adding org.apache.maven.artifact.handler.ArtifactHandlertest-jar
Adding org.apache.maven.artifact.handler.ArtifactHandlermaven-plugin
Adding org.apache.maven.artifact.handler.ArtifactHandlerpom
Adding org.apache.maven.artifact.handler.ArtifactHandlerjava-source
Adding org.apache.maven.artifact.handler.ArtifactHandlerjavadoc
Adding org.apache.maven.artifact.handler.ArtifactHandlerwar
Adding org.apache.maven.artifact.handler.ArtifactHandlerear
Adding org.apache.maven.artifact.handler.ArtifactHandlerejb-client
Adding org.apache.maven.artifact.handler.ArtifactHandlerrar
Adding org.apache.maven.artifact.handler.ArtifactHandlerpar
Adding org.apache.maven.artifact.handler.ArtifactHandlerejb3
Adding org.apache.maven.artifact.factory.ArtifactFactory
Adding org.apache.maven.artifact.resolver.ArtifactCollector
Adding org.apache.maven.project.artifact.ProjectArtifactFactorymaven-project
Adding org.apache.maven.project.MavenProjectHelper
Adding org.apache.maven.project.interpolation.ModelInterpolator
Adding org.apache.maven.project.injection.ModelDefaultsInjector
Adding org.apache.maven.project.injection.ProfileInjector
Adding org.apache.maven.project.MavenProjectBuilder
Adding org.apache.maven.profiles.activation.ProfileActivatoralways-on
Adding org.apache.maven.profiles.activation.ProfileActivatorjdk-prefix
Adding org.apache.maven.profiles.activation.ProfileActivatorsystem-property
Adding org.apache.maven.profiles.activation.ProfileActivatoros
Adding org.apache.maven.profiles.activation.ProfileActivatorfile
Adding org.apache.maven.project.inheritance.ModelInheritanceAssembler
Adding org.apache.maven.project.validation.ModelValidator
Adding org.apache.maven.project.path.PathTranslator
Adding org.apache.maven.artifact.metadata.ArtifactMetadataSourcemaven
Adding org.apache.maven.settings.MavenSettingsBuilder
Adding org.apache.maven.profiles.MavenProfilesBuilder
Adding org.apache.maven.artifact.manager.WagonManager
Adding org.apache.maven.artifact.manager.WagonProviderMapping
Adding org.apache.maven.artifact.repository.metadata.RepositoryMetadataManager
Adding org.apache.maven.artifact.transform.ArtifactTransformationsnapshot
Adding org.apache.maven.artifact.transform.ArtifactTransformationrelease
Adding org.apache.maven.artifact.transform.ArtifactTransformationlatest
Adding org.apache.maven.artifact.transform.ArtifactTransformationManager
Adding org.apache.maven.artifact.resolver.ArtifactResolver
Adding org.apache.maven.artifact.installer.ArtifactInstaller
Adding org.apache.maven.artifact.deployer.ArtifactDeployer
Adding org.apache.maven.artifact.repository.ArtifactRepositoryFactory
Adding org.codehaus.plexus.component.configurator.ComponentConfiguratorwagon
Adding org.apache.maven.plugin.registry.MavenPluginRegistryBuilder
Adding org.codehaus.plexus.component.configurator.ComponentConfiguratorbasic
Adding org.codehaus.plexus.component.configurator.ComponentConfiguratormap-oriented
Adding org.sonatype.plexus.build.incremental.BuildContextdefault
[INFO] Building jar: /Users/andrew/workspace/viskell/Code/target/viskell-0.1-jar-with-dependencies.jar
Component: org.apache.maven.artifact.repository.layout.ArtifactRepositoryLayoutdefault is already defined. Skipping.
Component: org.apache.maven.artifact.repository.layout.ArtifactRepositoryLayoutlegacy is already defined. Skipping.
Component: org.apache.maven.artifact.handler.manager.ArtifactHandlerManager is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerejb is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerjar is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlertest-jar is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlermaven-plugin is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerpom is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerjava-source is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerjavadoc is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerwar is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerear is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerejb-client is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerrar is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerpar is already defined. Skipping.
Component: org.apache.maven.artifact.handler.ArtifactHandlerejb3 is already defined. Skipping.
Component: org.apache.maven.artifact.factory.ArtifactFactory is already defined. Skipping.
Component: org.apache.maven.artifact.resolver.ArtifactCollector is already defined. Skipping.
Component: org.apache.maven.project.artifact.ProjectArtifactFactorymaven-project is already defined. Skipping.
Component: org.apache.maven.project.MavenProjectHelper is already defined. Skipping.
Component: org.apache.maven.project.interpolation.ModelInterpolator is already defined. Skipping.
Component: org.apache.maven.project.injection.ModelDefaultsInjector is already defined. Skipping.
Component: org.apache.maven.project.injection.ProfileInjector is already defined. Skipping.
Component: org.apache.maven.project.MavenProjectBuilder is already defined. Skipping.
Component: org.apache.maven.profiles.activation.ProfileActivatoralways-on is already defined. Skipping.
Component: org.apache.maven.profiles.activation.ProfileActivatorjdk-prefix is already defined. Skipping.
Component: org.apache.maven.profiles.activation.ProfileActivatorsystem-property is already defined. Skipping.
Component: org.apache.maven.profiles.activation.ProfileActivatoros is already defined. Skipping.
Component: org.apache.maven.profiles.activation.ProfileActivatorfile is already defined. Skipping.
Component: org.apache.maven.project.inheritance.ModelInheritanceAssembler is already defined. Skipping.
Component: org.apache.maven.project.validation.ModelValidator is already defined. Skipping.
Component: org.apache.maven.project.path.PathTranslator is already defined. Skipping.
Component: org.apache.maven.artifact.metadata.ArtifactMetadataSourcemaven is already defined. Skipping.
Component: org.apache.maven.settings.MavenSettingsBuilder is already defined. Skipping.
Component: org.apache.maven.profiles.MavenProfilesBuilder is already defined. Skipping.
Component: org.apache.maven.artifact.manager.WagonManager is already defined. Skipping.
Component: org.apache.maven.artifact.manager.WagonProviderMapping is already defined. Skipping.
Component: org.apache.maven.artifact.repository.metadata.RepositoryMetadataManager is already defined. Skipping.
Component: org.apache.maven.artifact.transform.ArtifactTransformationsnapshot is already defined. Skipping.
Component: org.apache.maven.artifact.transform.ArtifactTransformationrelease is already defined. Skipping.
Component: org.apache.maven.artifact.transform.ArtifactTransformationlatest is already defined. Skipping.
Component: org.apache.maven.artifact.transform.ArtifactTransformationManager is already defined. Skipping.
Component: org.apache.maven.artifact.resolver.ArtifactResolver is already defined. Skipping.
Component: org.apache.maven.artifact.installer.ArtifactInstaller is already defined. Skipping.
Component: org.apache.maven.artifact.deployer.ArtifactDeployer is already defined. Skipping.
Component: org.apache.maven.artifact.repository.ArtifactRepositoryFactory is already defined. Skipping.
Component: org.codehaus.plexus.component.configurator.ComponentConfiguratorwagon is already defined. Skipping.
Component: org.apache.maven.plugin.registry.MavenPluginRegistryBuilder is already defined. Skipping.
Component: org.codehaus.plexus.component.configurator.ComponentConfiguratorbasic is already defined. Skipping.
Component: org.codehaus.plexus.component.configurator.ComponentConfiguratormap-oriented is already defined. Skipping.
Component: org.sonatype.plexus.build.incremental.BuildContextdefault is already defined. Skipping.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:integration-test (default) @ viskell ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running nl.utwente.viskell.ui.components.DisplayBlockITCase
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.453 sec - in nl.utwente.viskell.ui.components.DisplayBlockITCase
Running nl.utwente.viskell.ui.components.ValueBlockITCase
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.373 sec - in nl.utwente.viskell.ui.components.ValueBlockITCase
Running nl.utwente.viskell.ui.ToplevelPaneITCase
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.32 sec - in nl.utwente.viskell.ui.ToplevelPaneITCase

Results :

Tests run: 11, Failures: 0, Errors: 0, Skipped: 0

[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19.1:verify (default) @ viskell ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent! The file encoding for reports output files should be provided by the POM property ${project.reporting.outputEncoding}.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.748 s
[INFO] Finished at: 2016-04-09T14:30:17+02:00
[INFO] Final Memory: 52M/566M
[INFO] ------------------------------------------------------------------------

**Comment by andrewdavidmackenzie** [comment]
Green now.

**Comment by wandernauta** [comment]
Strange... I've pulled xvfb out of master's .travis.yml, that should give us some clearer indication if a unit test is trying to hit UI.

At any rate, the code looks good - will merge.

**Comment by wandernauta** [comment]
Seems to work a charm, thanks again!

**Pull request merged**
